### ISSUE TITLE
Add locale option

### ISSUE THREAD

**Issue by RandomModderJDK** [GaspardMerten/date_field#44]
I would like rather  to use Monday as first day of the week. In the current situation sunday is the first day of the week. If you can change this, please tell me, because then i'm just dumb. 

I think it would be best to either use the locale tag from showDatePicker. Or make some parameter that just changes this behavior.

Thanks a lot!

**Comment by GaspardMerten** [comment]
Can't you use the override in your own code? I would have a tendency to think that such behaviour are not meant to be integrated in the package as the general approach is to use more general techniques like simply setting a Translation context above your instance of the Date Field widget.

If you think otherwise, please provide some code for me to easily test it :)

**Comment by RandomModderJDK** [comment]
Jup, you are right. Just learned how to internationalize an app properly.
