### ISSUE TITLE
change language

### ISSUE THREAD

**Issue by dukenebur** [GaspardMerten/date_field#52]
Hello! How I can change this?

![image](https://github.com/GaspardMerten/date_field/assets/43326504/c97ed834-329e-4750-bde5-a2ea8e763bd1)

**Comment by dukenebur** [comment]
I tried with something like this but it didn't work

Localizations.override(
        context: context,
        locale: const Locale('en'),
        child: Builder(
          builder: (context) {
            return DateTimeFormField(

**Comment by torbenkeller** [comment]
This does not work because your `Localizations.override` is around the `DateTimeFormField` and the date picker is a dialog with a new route. So when the date picker dialog tries to get the localizations with `MaterialLocalizations.of(context)`, it will get the localizations of your `MaterialApp`. To change the dialog language to english, set the locale on your `MaterialApp`.
